### ISSUE TITLE
[Feature Request] Append to highlight note instead of overwriting.

### ISSUE THREAD

**Issue by tjex** [OGKevin/obsidian-kobo-highlights-import#91]
Painfully realised that currently when importing highlights, the entire highlights page is generated fresh.
This means that any caret references, edits to highlight notes are broken / overwritten on each import.

This limits the usefulness of the plugin quite severely as the highlights page can only then ever be used as a visual reference to read and remind ones self (or copy and paste 😵), and therefore not truly integrated into the Obsidian / Zettelkasten note making workflow.

I think the simplest solution around this would be to simply append new highlights / notes to the highlights file instead of overwriting the whole file completely with a fresh import. From memory the Kindle highlights plugin works this way.

Is it realistic to look into something like this? Would be immensely appreciated.
I want to help, but my programming chops are probably not going to do much.

I'd be happy to update and extend the documentation if needs be though.

**Comment by OGKevin** [comment]
You're referencing https://github.com/hadynz/obsidian-kindle-plugin?

I would need to have a look on how they solved it and see.
But most likely I would need to keep a state somewhere of what has been exported and what not.

I'll have to do some brainstorming and come up with something.

**Comment by tjex** [comment]
yep, that one. 
Would be amazing man! 🙏
I'll also try have a look.

**Comment by tjex** [comment]
Considering the chapter names are returned from the book (ie values that are not user defined), could they be used as references for an incoming import?
eg: 
1. on import, reference the last highlight from the last chapter heading
2. check these against the incoming import (maybe the user deleted those highlights)
3. append the incoming highlight/note pairings that come after the latest highlight/note pairings to the file

not sure how to handle the `else` branch then in step 2. But will keep thinking.

**Comment by rsletta** [comment]
Hi, 
I found your plugin when doing my "let's see if there is something out there, before I start developing my own" check. I would like to contribute to your plugin if you allow it, rather than creating something similar myself. I came up with a naive implementation tonight that keeps edits including caret references, and have pushed my changes to my fork at https://github.com/rsletta/obsidian-kobo-highlights-import.

**Comment by OGKevin** [comment]
@rsletta yes please open a pull request! Contributions are always welcome. 

I did not have a chance yet to have a good look at this, so your start will certainly help.

**Comment by OGKevin** [comment]
@tjex are you available to test and see if it fulfils your use case? 
you can download the plugin from https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/1.6.0-beta.0 and replace `.obsidian/plugins/obsidian-kobo-highlights-importer-plugin/main.js` then restart the app.

**Comment by tjex** [comment]
hey. great that this got done! makes the plugin so much more valuable 🙏.

I tested:

1. Making a new highlight and note, that sit in between older and newer highlight+notes: works great (creates a new highlight and note in the markdown doc in the correct position.
2. edit a note of a highlight: updates the note in the markdown doc
3. deleting an annotation: the annotation does not get deleted from the markdown doc
4. changing the range of the highlighted text: the quote (highlighted text from book) does not update in the markdown doc

Features 1 and 2 are definitely the most useful. 3 and 4 would be nice to haves. I'm not sure how much more effort it would take to implement them. 

Also, just on a readability / UX standpoint, the `--> you can write text here blocks <--` should be replaced with something cleaner, like `Local note: (this text won't be deleted on resync`. And perhaps only in one spot *after* each highlight?

Perhaps this was already part of the plan, but just in case, it's worth pointing out for clarity!

**Comment by OGKevin** [comment]
> Also, just on a readability / UX standpoint, the --> you can write text here blocks <-- should be replaced with something cleaner, like Local note: (this text won't be deleted on resync. And perhaps only in one spot after each highlight?

It looks like I forgot to push a change 🤦🏾 
It’s supposed to be `%%` instead of `—>`, if not it will show in read mode, as in, %% is a comment marker.
Like shown here: https://github.com/OGKevin/obsidian-kobo-highlights-import/pull/107#issuecomment-1886984245

With the way it looks in the screenshot, do you still think the text needs to change due to UX?

---

Regarding deletion, if I understand the code correctly, the current implementation would remove everything within that ID marker if it goes missing from the database. What you’re describing, sounds like when you delete it via the e-reader, the e-reader might not actually delete the entry from the DB? I would need to play around with it and reproduce.

Do you mind creating a new issue so we can look into this?

---

I need to investigate your 4th point.
Based on the investigation that @rsletta did https://github.com/OGKevin/obsidian-kobo-highlights-import/pull/107#issuecomment-1506391674
And this: https://github.com/rsletta/obsidian-kobo-highlights-import/blob/6bc945f26436eaa74f677b585fca44b5e697f099/src/database/Highlight.test.ts#L488-L555

Updating the highlight should work if the ID’s are the same. I’ll see if I can reproduce your case with an actual end to end test case. 

I’ll create a followup issue for this one 👌🏾

**Comment by tjex** [comment]
> With the way it looks in the screenshot, do you still think the text needs to change due to UX?

I think wrapping in `%% ... %%` as you've done is good. Then at least in reader view, it's all neat. 

Will make a new issue. Thanks so much :)
